# FROM val01:5000/python-base-image:dev-base
FROM ddnirvana/python-base-image:dev-base-3.6_arm64

RUN mkdir /env && mkdir /code
COPY daemon-base.py /env
COPY src/ /code
COPY spin  /

# Prepare deps here
RUN pip install pyaes
