# FROM python:3.9.2-alpine
FROM python:3.6 

RUN pip3 install tornado==4.5.3 -i https://mirrors.aliyun.com/pypi/simple

# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
#    && apk add alpine-sdk python3-dev
